import type { Metadata } from "next";
import "./globals.css";
import ToasterConfig from "@/components/ToasterConfig";

import {Roboto , Poppins} from "next/font/google"

const roboto_init = Roboto({
  weight : "400" ,
  subsets : ["latin"] ,
  variable : "--font-roboto"
})

const poppins_init = Poppins({
  subsets : ["latin"] ,
  weight : "400" ,
  variable : "--font-poppins"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto_init.variable} ${poppins_init.variable}`}
      >
      <ToasterConfig />  
        {children}
      </body>
    </html>
  );
}
